version: 2.1

jobs:
  build-test:
    docker:
      - image: autotelic/circleci-base:0.0.1
    steps:
      - checkout
      - run:
          name: ping
          command: echo "pong"

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build-test
